"""Knowledge Intelligence Engine — understanding, reasoning, learning, validation.

Phases 16-17: Knowledge Intelligence + Autonomous Learning.

The engine continuously analyzes knowledge entries, learns from executions,
detects gaps/conflicts, and generates intelligence about the knowledge base.
"""

from __future__ import annotations

import asyncio
import hashlib
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from typing import Any

from core.logging import get_logger
from services.knowledge.models import (
    ConflictReport,
    KnowledgeEntry,
    KnowledgeEntryStatus,
    MemoryRecord,
)

_log = get_logger(__name__)

__all__ = [
    "AutonomousLearningEngine",
    "KnowledgeGap",
    "KnowledgeInsight",
    "KnowledgeIntelligenceEngine",
    "KnowledgeQualityReport",
    "Lesson",
    "Playbook",
]


@dataclass
class KnowledgeInsight:
    """An insight generated by the Knowledge Intelligence Engine."""

    insight_id: str = field(default_factory=lambda: hashlib.sha256(str(datetime.now(UTC)).encode()).hexdigest()[:12])
    category: str = ""  # understanding, reasoning, gap, conflict, quality, evolution
    finding: str = ""
    confidence: float = 0.5
    explanation: str = ""
    evidence: dict[str, Any] = field(default_factory=dict)
    detected_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def to_dict(self) -> dict[str, Any]:
        return {
            "insight_id": self.insight_id,
            "category": self.category,
            "finding": self.finding,
            "confidence": round(self.confidence, 4),
            "explanation": self.explanation,
            "evidence": dict(self.evidence),
            "detected_at": self.detected_at.isoformat(),
        }


@dataclass
class KnowledgeGap:
    """A detected gap in the knowledge base."""

    gap_id: str = field(default_factory=lambda: hashlib.sha256(str(datetime.now(UTC)).encode()).hexdigest()[:12])
    description: str = ""
    category: str = ""
    severity: str = "medium"
    suggested_action: str = ""
    detected_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def to_dict(self) -> dict[str, Any]:
        return {
            "gap_id": self.gap_id,
            "description": self.description,
            "category": self.category,
            "severity": self.severity,
            "suggested_action": self.suggested_action,
            "detected_at": self.detected_at.isoformat(),
        }


@dataclass
class KnowledgeQualityReport:
    """Quality assessment of the knowledge base."""

    total_entries: int = 0
    avg_quality: float = 0.0
    avg_freshness: float = 0.0
    avg_confidence: float = 0.0
    published_count: int = 0
    draft_count: int = 0
    archived_count: int = 0
    low_quality_count: int = 0
    stale_count: int = 0
    duplicate_count: int = 0
    missing_metadata_count: int = 0
    gaps: list[KnowledgeGap] = field(default_factory=list)
    conflicts: list[ConflictReport] = field(default_factory=list)
    recommendations: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "total_entries": self.total_entries,
            "avg_quality": round(self.avg_quality, 4),
            "avg_freshness": round(self.avg_freshness, 4),
            "avg_confidence": round(self.avg_confidence, 4),
            "published_count": self.published_count,
            "draft_count": self.draft_count,
            "archived_count": self.archived_count,
            "low_quality_count": self.low_quality_count,
            "stale_count": self.stale_count,
            "duplicate_count": self.duplicate_count,
            "missing_metadata_count": self.missing_metadata_count,
            "gaps": [g.to_dict() for g in self.gaps],
            "conflicts": [c.to_dict() for c in self.conflicts],
            "recommendations": list(self.recommendations),
        }


@dataclass
class Lesson:
    """A lesson learned from execution history."""

    lesson_id: str = field(default_factory=lambda: hashlib.sha256(str(datetime.now(UTC)).encode()).hexdigest()[:12])
    category: str = ""  # best_practice, anti_pattern, recovery, troubleshooting, optimization
    title: str = ""
    content: str = ""
    source: str = ""  # execution, mission, failure, approval, review
    confidence: float = 0.5
    evidence: dict[str, Any] = field(default_factory=dict)
    tags: list[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def to_dict(self) -> dict[str, Any]:
        return {
            "lesson_id": self.lesson_id,
            "category": self.category,
            "title": self.title,
            "content": self.content,
            "source": self.source,
            "confidence": round(self.confidence, 4),
            "evidence": dict(self.evidence),
            "tags": list(self.tags),
            "created_at": self.created_at.isoformat(),
        }


@dataclass
class Playbook:
    """A recovery/optimization playbook generated from lessons."""

    playbook_id: str = field(default_factory=lambda: hashlib.sha256(str(datetime.now(UTC)).encode()).hexdigest()[:12])
    title: str = ""
    description: str = ""
    steps: list[dict[str, Any]] = field(default_factory=list)
    trigger_conditions: list[str] = field(default_factory=list)
    lessons: list[str] = field(default_factory=list)  # lesson_ids
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def to_dict(self) -> dict[str, Any]:
        return {
            "playbook_id": self.playbook_id,
            "title": self.title,
            "description": self.description,
            "steps": list(self.steps),
            "trigger_conditions": list(self.trigger_conditions),
            "lessons": list(self.lessons),
            "created_at": self.created_at.isoformat(),
        }


class KnowledgeIntelligenceEngine:
    """Analyzes knowledge for understanding, gaps, conflicts, and quality.

    Phase 16: Knowledge Intelligence Engine.
    """

    def __init__(self) -> None:
        self._entries: list[KnowledgeEntry] = []
        self._lock = asyncio.Lock()

    async def ingest_entries(self, entries: list[KnowledgeEntry]) -> None:
        async with self._lock:
            self._entries = list(entries)

    async def analyze_all(self) -> list[KnowledgeInsight]:
        """Run all intelligence analyses."""
        insights: list[KnowledgeInsight] = []
        insights.extend(await self.detect_gaps())
        insights.extend(await self.detect_conflicts())
        insights.extend(await self.analyze_freshness())
        insights.extend(await self.analyze_coverage())
        insights.extend(await self.discover_relationships())
        return insights

    async def detect_gaps(self) -> list[KnowledgeInsight]:
        """Detect gaps in knowledge coverage."""
        insights: list[KnowledgeInsight] = []
        if not self._entries:
            return [KnowledgeInsight(
                category="gap", finding="Knowledge base is empty",
                confidence=1.0, explanation="No knowledge entries have been created yet.",
            )]
        # Check for entries without summaries
        no_summary = [e for e in self._entries if not e.summary]
        if no_summary:
            insights.append(KnowledgeInsight(
                category="gap",
                finding=f"{len(no_summary)} entries lack summaries",
                confidence=0.8,
                explanation="Entries without summaries are harder to discover via search.",
                evidence={"count": len(no_summary)},
            ))
        # Check for entries without labels
        no_labels = [e for e in self._entries if not e.labels]
        if no_labels:
            insights.append(KnowledgeInsight(
                category="gap",
                finding=f"{len(no_labels)} entries lack labels/tags",
                confidence=0.7,
                explanation="Entries without labels are harder to categorize and filter.",
                evidence={"count": len(no_labels)},
            ))
        # Check for stale entries (not updated in 90 days)
        cutoff = datetime.now(UTC) - timedelta(days=90)
        stale = [e for e in self._entries if e.updated_at < cutoff]
        if stale:
            insights.append(KnowledgeInsight(
                category="gap",
                finding=f"{len(stale)} entries are stale (not updated in 90+ days)",
                confidence=0.6,
                explanation="Stale knowledge may be outdated and should be reviewed.",
                evidence={"count": len(stale), "cutoff_days": 90},
            ))
        return insights

    async def detect_conflicts(self) -> list[KnowledgeInsight]:
        """Detect conflicting knowledge entries."""
        insights: list[KnowledgeInsight] = []
        # Group by title
        by_title: dict[str, list[KnowledgeEntry]] = defaultdict(list)
        for entry in self._entries:
            if entry.title:
                by_title[entry.title].append(entry)
        for title, entries in by_title.items():
            if len(entries) > 1:
                # Check if content differs
                contents = {e.content[:200] for e in entries}
                if len(contents) > 1:
                    insights.append(KnowledgeInsight(
                        category="conflict",
                        finding=f"Conflicting entries for '{title}' ({len(entries)} versions)",
                        confidence=0.7,
                        explanation=f"Multiple entries with title '{title}' have different content.",
                        evidence={"title": title, "count": len(entries)},
                    ))
        return insights

    async def analyze_freshness(self) -> list[KnowledgeInsight]:
        """Analyze knowledge freshness."""
        insights: list[KnowledgeInsight] = []
        if not self._entries:
            return insights
        now = datetime.now(UTC)
        ages = [(now - e.updated_at).total_seconds() / 86400 for e in self._entries]
        avg_age = sum(ages) / len(ages)
        if avg_age > 60:
            insights.append(KnowledgeInsight(
                category="quality",
                finding=f"Average knowledge age is {avg_age:.0f} days — consider refreshing",
                confidence=0.7,
                explanation="Old knowledge may not reflect current system state.",
                evidence={"avg_age_days": round(avg_age, 1)},
            ))
        return insights

    async def analyze_coverage(self) -> list[KnowledgeInsight]:
        """Analyze knowledge coverage by category."""
        insights: list[KnowledgeInsight] = []
        by_category: dict[str, int] = Counter(e.category for e in self._entries if e.category)
        if not by_category:
            insights.append(KnowledgeInsight(
                category="gap",
                finding="No categorized knowledge entries",
                confidence=0.8,
                explanation="All entries lack category assignment.",
            ))
        else:
            for cat, count in sorted(by_category.items(), key=lambda x: x[1], reverse=True):
                if count < 3:
                    insights.append(KnowledgeInsight(
                        category="gap",
                        finding=f"Category '{cat}' has only {count} entries",
                        confidence=0.5,
                        explanation="Low coverage in this category may indicate a knowledge gap.",
                        evidence={"category": cat, "count": count},
                    ))
        return insights

    async def discover_relationships(self) -> list[KnowledgeInsight]:
        """Discover relationships between knowledge entries."""
        insights: list[KnowledgeInsight] = []
        # Find entries with shared labels
        label_groups: dict[str, list[str]] = defaultdict(list)
        for entry in self._entries:
            for label in entry.labels:
                label_groups[label].append(entry.entry_id)
        for label, entry_ids in label_groups.items():
            if len(entry_ids) >= 3:
                insights.append(KnowledgeInsight(
                    category="relationship",
                    finding=f"Label '{label}' connects {len(entry_ids)} entries",
                    confidence=0.6,
                    explanation=f"Entries sharing label '{label}' may be related.",
                    evidence={"label": label, "entry_count": len(entry_ids)},
                ))
        return insights

    async def quality_report(self) -> KnowledgeQualityReport:
        """Generate a comprehensive quality report."""
        report = KnowledgeQualityReport(total_entries=len(self._entries))
        if not self._entries:
            return report
        # Quality scores
        for entry in self._entries:
            score = 0.0
            if entry.title:
                score += 0.1
            if entry.content and len(entry.content) > 50:
                score += 0.2
            if entry.summary:
                score += 0.1
            if entry.labels:
                score += 0.1
            if entry.reviewed_by:
                score += 0.2
            if entry.references:
                score += 0.1
            if entry.source_confidence > 0.7:
                score += 0.2
            entry.quality_score = min(1.0, score)
            if entry.status == KnowledgeEntryStatus.PUBLISHED.value:
                report.published_count += 1
            elif entry.status == KnowledgeEntryStatus.DRAFT.value:
                report.draft_count += 1
            elif entry.status == KnowledgeEntryStatus.ARCHIVED.value:
                report.archived_count += 1
            if entry.quality_score < 0.4:
                report.low_quality_count += 1
            if not entry.labels:
                report.missing_metadata_count += 1
        report.avg_quality = sum(e.quality_score for e in self._entries) / len(self._entries)
        report.avg_confidence = sum(e.source_confidence for e in self._entries) / len(self._entries)
        # Freshness
        now = datetime.now(UTC)
        ages = [(now - e.updated_at).total_seconds() / 86400 for e in self._entries]
        report.avg_freshness = 1.0 - min(1.0, sum(ages) / len(ages) / 365)
        stale_cutoff = now - timedelta(days=90)
        report.stale_count = sum(1 for e in self._entries if e.updated_at < stale_cutoff)
        # Duplicates
        content_hashes = [hashlib.sha256(e.content[:500].encode()).hexdigest()[:16] for e in self._entries]
        report.duplicate_count = len(content_hashes) - len(set(content_hashes))
        # Gaps
        gap_insights = await self.detect_gaps()
        report.gaps = [
            KnowledgeGap(
                description=i.finding,
                category=i.category,
                severity="medium" if i.confidence > 0.7 else "low",
                suggested_action="Review and address the identified gap",
            )
            for i in gap_insights
        ]
        # Recommendations
        if report.low_quality_count > 0:
            report.recommendations.append(f"Improve {report.low_quality_count} low-quality entries")
        if report.stale_count > 0:
            report.recommendations.append(f"Review {report.stale_count} stale entries")
        if report.duplicate_count > 0:
            report.recommendations.append(f"Merge {report.duplicate_count} duplicate entries")
        if report.missing_metadata_count > 0:
            report.recommendations.append(f"Add metadata to {report.missing_metadata_count} entries")
        return report


class AutonomousLearningEngine:
    """Learns from every execution and generates lessons + playbooks.

    Phase 17: Autonomous Knowledge Learning.
    """

    def __init__(self) -> None:
        self._lessons: list[Lesson] = []
        self._playbooks: list[Playbook] = []
        self._lock = asyncio.Lock()

    async def learn_from_execution(
        self,
        *,
        goal: str = "",
        success: bool = True,
        agent_id: str = "",
        provider: str = "",
        duration_s: float = 0.0,
        cost_usd: float = 0.0,
        error: str | None = None,
        retries: int = 0,
        feedback: str | None = None,
    ) -> Lesson:
        """Generate a lesson from an execution."""
        if success:
            lesson = Lesson(
                category="best_practice",
                title=f"Successful execution: {goal[:60]}",
                content=f"Goal '{goal}' succeeded with agent '{agent_id}' "
                        f"and provider '{provider}' in {duration_s:.2f}s costing ${cost_usd:.4f}.",
                source="execution",
                confidence=0.7,
                evidence={
                    "agent_id": agent_id, "provider": provider,
                    "duration_s": duration_s, "cost_usd": cost_usd,
                },
                tags=["success", agent_id, provider] if agent_id else ["success"],
            )
        else:
            lesson = Lesson(
                category="anti_pattern" if retries > 2 else "troubleshooting",
                title=f"Failed execution: {goal[:60]}",
                content=f"Goal '{goal}' failed after {retries} retries. "
                        f"Error: {error or 'unknown'}. "
                        f"Agent: {agent_id}, Provider: {provider}.",
                source="execution",
                confidence=0.8,
                evidence={
                    "agent_id": agent_id, "provider": provider,
                    "error": error, "retries": retries,
                },
                tags=["failure", "troubleshooting"] + ([agent_id] if agent_id else []),
            )
        async with self._lock:
            self._lessons.append(lesson)
        return lesson

    async def learn_from_approval(
        self,
        *,
        action: str = "",
        approved: bool = True,
        risk_level: str = "medium",
        reason: str = "",
    ) -> Lesson:
        """Generate a lesson from an approval decision."""
        lesson = Lesson(
            category="best_practice" if approved else "anti_pattern",
            title=f"Approval {'granted' if approved else 'rejected'}: {action[:60]}",
            content=f"Action '{action}' was {'approved' if approved else 'rejected'} "
                    f"(risk: {risk_level}). Reason: {reason or 'none given'}.",
            source="approval",
            confidence=0.6,
            evidence={"action": action, "approved": approved, "risk_level": risk_level},
            tags=["approval", risk_level],
        )
        async with self._lock:
            self._lessons.append(lesson)
        return lesson

    async def learn_from_feedback(
        self,
        *,
        target: str = "",
        feedback: str = "",
        rating: int = 0,
    ) -> Lesson:
        """Generate a lesson from user feedback."""
        lesson = Lesson(
            category="best_practice" if rating >= 4 else "anti_pattern",
            title=f"Feedback on '{target[:60]}' (rating: {rating})",
            content=f"User feedback: '{feedback}'. Rating: {rating}/5.",
            source="user_feedback",
            confidence=0.7,
            evidence={"target": target, "rating": rating},
            tags=["feedback", "user"],
        )
        async with self._lock:
            self._lessons.append(lesson)
        return lesson

    async def generate_playbook(
        self,
        *,
        title: str,
        description: str,
        trigger_conditions: list[str],
        steps: list[dict[str, Any]],
    ) -> Playbook:
        """Generate a playbook from accumulated lessons."""
        # Find relevant lessons
        relevant = [
            lesson for lesson in self._lessons
            if any(tc.lower() in lesson.content.lower() for tc in trigger_conditions)
        ]
        playbook = Playbook(
            title=title,
            description=description,
            steps=steps,
            trigger_conditions=trigger_conditions,
            lessons=[lesson.lesson_id for lesson in relevant],
        )
        async with self._lock:
            self._playbooks.append(playbook)
        return playbook

    async def merge_duplicates(self) -> int:
        """Merge duplicate lessons."""
        merged = 0
        async with self._lock:
            by_content: dict[str, list[Lesson]] = defaultdict(list)
            for lesson in self._lessons:
                content_hash = hashlib.sha256(lesson.content.encode()).hexdigest()[:16]
                by_content[content_hash].append(lesson)
            for _hash, duplicates in by_content.items():
                if len(duplicates) <= 1:
                    continue
                # Keep highest confidence
                duplicates.sort(key=lambda lesson: lesson.confidence, reverse=True)
                self._lessons = [lesson for lesson in self._lessons if lesson.lesson_id not in {d.lesson_id for d in duplicates[1:]}]
                merged += len(duplicates) - 1
        return merged

    async def get_lessons(
        self,
        *,
        category: str | None = None,
        limit: int = 50,
    ) -> list[Lesson]:
        async with self._lock:
            lessons = list(self._lessons)
        if category:
            lessons = [lesson for lesson in lessons if lesson.category == category]
        lessons.sort(key=lambda lesson: lesson.confidence, reverse=True)
        return lessons[:limit]

    async def get_playbooks(self, limit: int = 20) -> list[Playbook]:
        async with self._lock:
            return list(self._playbooks[:limit])

    async def stats(self) -> dict[str, Any]:
        async with self._lock:
            by_category: dict[str, int] = Counter(lesson.category for lesson in self._lessons)
            return {
                "total_lessons": len(self._lessons),
                "total_playbooks": len(self._playbooks),
                "by_category": dict(by_category),
                "avg_confidence": sum(lesson.confidence for lesson in self._lessons) / max(1, len(self._lessons)),
            }


class RecommendationEngine:
    """Recommends relevant knowledge, missions, agents, etc.

    Phase 22: Knowledge Recommendation Engine.
    """

    def __init__(
        self,
        learning_engine: AutonomousLearningEngine,
    ) -> None:
        self._learning = learning_engine
        self._entries: list[KnowledgeEntry] = []
        self._memories: list[MemoryRecord] = []

    async def ingest(self, entries: list[KnowledgeEntry], memories: list[MemoryRecord]) -> None:
        self._entries = entries
        self._memories = memories

    async def recommend_all(self, context: str = "") -> list[dict[str, Any]]:
        """Generate all recommendations for a given context."""
        recs: list[dict[str, Any]] = []
        recs.extend(await self.recommend_documents(context))
        recs.extend(await self.recommend_lessons(context))
        recs.extend(await self.recommend_playbooks(context))
        recs.extend(await self.recommend_memories(context))
        return recs

    async def recommend_documents(self, context: str) -> list[dict[str, Any]]:
        """Recommend relevant knowledge entries."""
        context_lower = context.lower()
        results: list[dict[str, Any]] = []
        for entry in self._entries:
            score = 0.0
            if context_lower in entry.title.lower():
                score += 0.5
            if context_lower in entry.content.lower():
                score += 0.3
            if any(context_lower in label.lower() for label in entry.labels):
                score += 0.2
            if score > 0:
                results.append({
                    "type": "document",
                    "entry_id": entry.entry_id,
                    "title": entry.title,
                    "score": round(score, 4),
                    "confidence": round(entry.source_confidence, 4),
                })
        results.sort(key=lambda x: x["score"], reverse=True)
        return results[:10]

    async def recommend_lessons(self, context: str) -> list[dict[str, Any]]:
        """Recommend relevant lessons learned."""
        context_lower = context.lower()
        lessons = await self._learning.get_lessons(limit=100)
        results: list[dict[str, Any]] = []
        for lesson in lessons:
            score = 0.0
            if context_lower in lesson.content.lower():
                score += 0.5
            if context_lower in lesson.title.lower():
                score += 0.3
            if any(context_lower in tag.lower() for tag in lesson.tags):
                score += 0.2
            if score > 0:
                results.append({
                    "type": "lesson",
                    "lesson_id": lesson.lesson_id,
                    "title": lesson.title,
                    "category": lesson.category,
                    "score": round(score * lesson.confidence, 4),
                })
        results.sort(key=lambda x: x["score"], reverse=True)
        return results[:10]

    async def recommend_playbooks(self, context: str) -> list[dict[str, Any]]:
        """Recommend relevant playbooks."""
        context_lower = context.lower()
        playbooks = await self._learning.get_playbooks()
        results: list[dict[str, Any]] = []
        for pb in playbooks:
            score = 0.0
            if context_lower in pb.title.lower():
                score += 0.4
            if context_lower in pb.description.lower():
                score += 0.3
            if any(context_lower in tc.lower() for tc in pb.trigger_conditions):
                score += 0.3
            if score > 0:
                results.append({
                    "type": "playbook",
                    "playbook_id": pb.playbook_id,
                    "title": pb.title,
                    "score": round(score, 4),
                })
        results.sort(key=lambda x: x["score"], reverse=True)
        return results[:5]

    async def recommend_memories(self, context: str) -> list[dict[str, Any]]:
        """Recommend relevant memories."""
        context_lower = context.lower()
        results: list[dict[str, Any]] = []
        for mem in self._memories:
            score = 0.0
            if context_lower in mem.content.lower():
                score += 0.5
            if any(context_lower in tag.lower() for tag in mem.tags):
                score += 0.3
            score += mem.importance * 0.2
            if score > 0.1:
                results.append({
                    "type": "memory",
                    "memory_id": mem.memory_id,
                    "memory_type": mem.memory_type,
                    "content_snippet": mem.content[:100],
                    "score": round(score, 4),
                })
        results.sort(key=lambda x: x["score"], reverse=True)
        return results[:10]
