"""Agent SDK — scaffolding and utilities for writing new agent plugins.

The Agent SDK makes it easy to write a new agent that wraps an external
CLI, a remote service, or an in-process Python class. It provides:

  - Templates for each implementation style (InProcess, Subprocess, Remote)
  - A ``scaffold`` function that generates a new agent plugin directory
  - Test harness utilities for testing agents without real LLM calls

Usage:
    from services.agent_sdk import scaffold_agent

    # Scaffold a new agent plugin
    scaffold_agent(
        name='my-agent',
        agent_type='coding',
        style='subprocess',
        output_dir=Path('./plugins/my-agent'),
    )
"""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

__all__ = ["scaffold_agent", "AGENT_TEMPLATES"]


def scaffold_agent(
    *,
    name: str,
    agent_type: str,
    style: str = "in_process",
    output_dir: Path,
) -> Path:
    """Scaffold a new agent plugin directory.

    Args:
        name: the agent name (e.g. 'my-agent').
        agent_type: one of the 16 agent types (coding, desktop, research, etc.).
        style: implementation style ('in_process', 'subprocess', 'remote').
        output_dir: where to create the plugin directory.

    Returns:
        The path to the created plugin directory.
    """
    plugin_dir = output_dir / name
    plugin_dir.mkdir(parents=True, exist_ok=True)

    # Generate plugin.json manifest
    manifest = dedent(f'''\
        {{
            "name": "{name}",
            "version": "0.1.0",
            "description": "{name} agent plugin",
            "vendor": "",
            "provides_agents": ["{name.replace("-", "_")}_plugin.agent.{name.title().replace("-", "")}Agent"],
            "entry_point": "{name.replace("-", "_")}_plugin"
        }}
    ''')
    (plugin_dir / "plugin.json").write_text(manifest, encoding="utf-8")

    # Generate __init__.py
    init_py = dedent(f'''\
        """{name} agent plugin."""
    ''')
    (plugin_dir / "__init__.py").write_text(init_py, encoding="utf-8")

    # Generate the agent module
    agent_module = AGENT_TEMPLATES.get(style, AGENT_TEMPLATES["in_process"])
    agent_code = agent_module.format(
        name=name,
        Name=name.title().replace("-", ""),
        agent_type=agent_type.upper(),
    )
    agent_dir = plugin_dir / "agent"
    agent_dir.mkdir(exist_ok=True)
    (agent_dir / "__init__.py").write_text('"""Agent module."""\n', encoding="utf-8")
    (agent_dir / "agent.py").write_text(agent_code, encoding="utf-8")

    # Generate README
    readme = dedent(f"""\
        # {name} Agent Plugin

        A {agent_type} agent for AAiOS.

        ## Installation

        Copy this directory to your AAiOS plugins directory:
        ```
        cp -r . $AAiOS_DATA/plugins/installed/{name}
        ```

        Then enable it:
        ```
        aaios plugins enable {name}
        ```
    """)
    (plugin_dir / "README.md").write_text(readme, encoding="utf-8")

    return plugin_dir


# Template strings for each implementation style
AGENT_TEMPLATES: dict[str, str] = {
    "in_process": dedent('''\
        """{Name} — an in-process {agent_type} agent.

        Generated by the Agent SDK. Implements the GenericAgent interface
        via InProcessAgent base class.
        """

        from __future__ import annotations

        from agents._base.in_process import InProcessAgent
        from core.contracts.agent import AgentIdentity, AgentType, CapabilityManifest, Capability
        from core.contracts.task import TaskRequest, TaskResult, TaskResultStatus


        class {Name}Agent(InProcessAgent):
            """A {name} agent (in-process)."""

            def __init__(self) -> None:
                identity = AgentIdentity(
                    agent_id='{name}-v1',
                    agent_type=AgentType.{agent_type},
                    implementation_name='{Name}',
                    version='0.1.0',
                )
                super().__init__(identity)

            async def _build_manifest(self) -> CapabilityManifest:
                return CapabilityManifest(
                    identity=self._identity,
                    capabilities=[
                        Capability(namespace='{name}.execute', description='Execute a {name} task'),
                    ],
                )

            async def _execute(self, request: TaskRequest) -> TaskResult:
                # Implement the actual agent logic here
                return TaskResult(
                    task_id=request.id,
                    status=TaskResultStatus.SUCCESS,
                    output={{'goal': request.goal, 'result': 'not implemented yet'}},
                )
    '''),
    "subprocess": dedent('''\
        """{Name} — a subprocess-bridge {agent_type} agent.

        Generated by the Agent SDK. Implements the GenericAgent interface
        via SubprocessBridgeAgent base class. Wraps an external CLI.
        """

        from __future__ import annotations

        import os
        from agents._base.subprocess_bridge import SubprocessBridgeAgent
        from core.contracts.agent import AgentIdentity, AgentType, CapabilityManifest, Capability
        from core.contracts.health import HealthReport
        from core.contracts.task import TaskRequest, TaskResult, TaskResultStatus


        class {Name}Agent(SubprocessBridgeAgent):
            """A {name} agent (subprocess bridge)."""

            def __init__(self) -> None:
                identity = AgentIdentity(
                    agent_id='{name}-v1',
                    agent_type=AgentType.{agent_type},
                    implementation_name='{Name}',
                    version='0.1.0',
                )
                super().__init__(identity)

            async def _on_initialize(self) -> None:
                # Spawn the CLI subprocess
                self._health = HealthReport.healthy()

            async def _build_manifest(self) -> CapabilityManifest:
                return CapabilityManifest(
                    identity=self._identity,
                    capabilities=[
                        Capability(namespace='{name}.execute', description='Execute a {name} task'),
                    ],
                )

            async def _rpc_call(self, method: str, params: dict) -> object:
                # Send JSON-RPC to the subprocess
                return {{'mock': True}}

            async def _execute(self, request: TaskRequest) -> TaskResult:
                # Implement via _rpc_call
                return TaskResult(
                    task_id=request.id,
                    status=TaskResultStatus.SUCCESS,
                    output={{'goal': request.goal, 'result': 'not implemented yet'}},
                )
    '''),
    "remote": dedent('''\
        """{Name} — a remote-service {agent_type} agent.

        Generated by the Agent SDK. Implements the GenericAgent interface
        via RemoteServiceAgent base class. Talks to a remote HTTP API.
        """

        from __future__ import annotations

        from agents._base.remote_service import RemoteServiceAgent
        from core.contracts.agent import AgentIdentity, AgentType, CapabilityManifest, Capability
        from core.contracts.task import TaskRequest, TaskResult, TaskResultStatus


        class {Name}Agent(RemoteServiceAgent):
            """A {name} agent (remote service)."""

            def __init__(self) -> None:
                identity = AgentIdentity(
                    agent_id='{name}-v1',
                    agent_type=AgentType.{agent_type},
                    implementation_name='{Name}',
                    version='0.1.0',
                )
                # Set the endpoint
                super().__init__(identity, endpoint='http://localhost:8000')

            async def _build_manifest(self) -> CapabilityManifest:
                return CapabilityManifest(
                    identity=self._identity,
                    capabilities=[
                        Capability(namespace='{name}.execute', description='Execute a {name} task'),
                    ],
                )

            async def _call_remote(self, method: str, payload: dict) -> object:
                # Make the HTTP call
                return {{'mock': True}}

            async def _execute(self, request: TaskRequest) -> TaskResult:
                # Implement via _call_remote
                return TaskResult(
                    task_id=request.id,
                    status=TaskResultStatus.SUCCESS,
                    output={{'goal': request.goal, 'result': 'not implemented yet'}},
                )
    '''),
}
